// <auto-generated />
namespace Matricula_Proyecto.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class SolucionBD : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SolucionBD));
        
        string IMigrationMetadata.Id
        {
            get { return "202308162113018_SolucionBD"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
